Fixing an error (Assets/Scripts/SoundManager)
UnassignedReferenceException: The variable blocSliderValue of SoundManager has not been assigned.
You probably need to assign the blocSliderValue variable of the SoundManager script in the inspector.
UnityEngine.Object+MarshalledUnityObject.TryThrowEditorNullExceptionObject (UnityEngine.Object unityObj, System.String parameterName) (at <84f0d810adef4e6c8deab33e4ae93f7c>:0)
UnityEngine.Bindings.ThrowHelper.ThrowNullReferenceException (System.Object obj) (at <84f0d810adef4e6c8deab33e4ae93f7c>:0)
UnityEngine.GameObject.SetActive (System.Boolean value) (at <84f0d810adef4e6c8deab33e4ae93f7c>:0)
SoundManager.ApplySettings () (at Assets/Scripts/SoundManager.cs:43)
SoundManager.Start () (at Assets/Scripts/SoundManager.cs:21)